# Generated by Django 5.0.7 on 2024-08-28 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 28, 11, 54, 48, 53423, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
